txt:
  time_independent:
    128:
      train: ../data/predictions/txt/time_indipendent/train_pred_model-2026-05-31-embdim=None_time_independent_txt_mod4-epoch=010-val_combined_loss=1.5085_txt_dim=128_proj_emb_step=.zip
      val: ../data/predictions/txt/time_indipendent/val_pred_model-2026-05-31-embdim=None_time_independent_txt_mod4-epoch=010-val_combined_loss=1.5085_txt_dim=128_proj_emb_step=.zip
    256:
      train: ../data/predictions/txt/time_indipendent/train_pred_model-2026-05-31-embdim=None_time_independent_txt_mod4-epoch=020-val_combined_loss=1.4107_txt_dim=256_proj_emb_step=.zip
      val: ../data/predictions/txt/time_indipendent/val_pred_model-2026-05-31-embdim=None_time_independent_txt_mod4-epoch=020-val_combined_loss=1.4107_txt_dim=256_proj_emb_step=.zip
  lag1:
    128:
      train: ../data/predictions/txt/lag1/train_pred_model-2026-05-31-embdim=None_lag1_txt_mod4-epoch=020-val_combined_loss=0.8961_txt_dim=128_proj_emb_step=.zip
      val: ../data/predictions/txt/lag1/val_pred_model-2026-05-31-embdim=None_lag1_txt_mod4-epoch=020-val_combined_loss=0.8961_txt_dim=128_proj_emb_step=.zip
    256:
      train: ../data/predictions/txt/lag1/train_pred_model-2026-05-31-embdim=None_lag1_txt_mod4-epoch=022-val_combined_loss=0.5825_txt_dim=256_proj_emb_step=.zip
      val: ../data/predictions/txt/lag1/val_pred_model-2026-05-31-embdim=None_lag1_txt_mod4-epoch=022-val_combined_loss=0.5825_txt_dim=256_proj_emb_step=.zip
txtimg:
  time_independent:
    128:
      train: ../data/predictions/txtimg/time_indipendent/train_pred_model-2026-05-31-embdim=None_time_independent_txtimg_mod4-epoch=013-val_combined_loss=1.0674_txtimg_dim=128_proj_emb_step=.zip
      val: ../data/predictions/txtimg/time_indipendent/val_pred_model-2026-05-31-embdim=None_time_independent_txtimg_mod4-epoch=013-val_combined_loss=1.0674_txtimg_dim=128_proj_emb_step=.zip
    256:
      train: ../data/predictions/txtimg/time_indipendent/train_pred_model-2026-05-31-embdim=None_time_independent_txtimg_mod4-epoch=012-val_combined_loss=1.0458_txtimg_dim=256_proj_emb_step=.zip
      val: ../data/predictions/txtimg/time_indipendent/val_pred_model-2026-05-31-embdim=None_time_independent_txtimg_mod4-epoch=012-val_combined_loss=1.0458_txtimg_dim=256_proj_emb_step=.zip
  lag1:
    128:
      train: ../data/predictions/txtimg/lag1/train_pred_model-2026-05-31-embdim=None_lag1_txtimg_mod4-epoch=008-val_combined_loss=0.8912_txtimg_dim=128_proj_emb_step=.zip
      val: ../data/predictions/txtimg/lag1/val_pred_model-2026-05-31-embdim=None_lag1_txtimg_mod4-epoch=008-val_combined_loss=0.8912_txtimg_dim=128_proj_emb_step=.zip
    256:
      train: ../data/predictions/txtimg/lag1/train_pred_model-2026-05-31-embdim=None_lag1_txtimg_mod4-epoch=007-val_combined_loss=0.8808_txtimg_dim=256_proj_emb_step=.zip
      val: ../data/predictions/txtimg/lag1/val_pred_model-2026-05-31-embdim=None_lag1_txtimg_mod4-epoch=007-val_combined_loss=0.8808_txtimg_dim=256_proj_emb_step=.zip
diff_txt:
  time_independent:
    train: ../data/predictions/txt/time_indipendent/pred_diff_shoes-diff-model-txt_2026-05-31-embdim=768_lag1-epoch=010-val_combined_loss=0.2507_txt_invariant_train.zip
    val: ../data/predictions/txt/time_indipendent/pred_diff_shoes-diff-model-txt_2026-05-31-embdim=768_lag1-epoch=010-val_combined_loss=0.2507_txt_invariant_val.zip
  lag1:
    train: ../data/predictions/txt/lag1/pred_diff_shoes-diff-model-txt_2026-05-31-embdim=768_lag1-epoch=015-val_combined_loss=0.2369_txt_lag1_train.zip
    val: ../data/predictions/txt/lag1/pred_diff_shoes-diff-model-txt_2026-05-31-embdim=768_lag1-epoch=015-val_combined_loss=0.2369_txt_lag1_val.zip
diff_txtimg:
  time_independent:
    train: ../data/predictions/txtimg/time_indipendent/pred_diff_shoes-diff-model-txtimg_2026-05-31-embdim=768_lag1-epoch=011-val_combined_loss=0.2498_txtimg_invariant_train.zip
    val: ../data/predictions/txtimg/time_indipendent/pred_diff_shoes-diff-model-txtimg_2026-05-31-embdim=768_lag1-epoch=011-val_combined_loss=0.2498_txtimg_invariant_val.zip
  lag1:
    train: ../data/predictions/txtimg/lag1/pred_diff_shoes-diff-model-txtimg_2026-05-31-embdim=768_lag1-epoch=015-val_combined_loss=0.2377_txtimg_lag1_train.zip
    val: ../data/predictions/txtimg/lag1/pred_diff_shoes-diff-model-txtimg_2026-05-31-embdim=768_lag1-epoch=015-val_combined_loss=0.2377_txtimg_lag1_val.zip
